"""garage61 auth table 3

Revision ID: 1575f1adb228
Revises: daf0404f1743
Create Date: 2024-09-20 08:09:57.403885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1575f1adb228'
down_revision: Union[str, None] = 'daf0404f1743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'garage61_user', ['linked_account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'garage61_user', type_='unique')
    # ### end Alembic commands ###
