"""weeks extension

Revision ID: 3a38c52e6d69
Revises: 69d6f3465710
Create Date: 2024-09-16 22:02:08.212621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a38c52e6d69'
down_revision: Union[str, None] = '69d6f3465710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week', sa.Column('car_id', sa.Integer(), nullable=False))
    op.add_column('week', sa.Column('track_id', sa.Integer(), nullable=False))
    op.add_column('week', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('week', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    op.create_foreign_key(None, 'week', 'track', ['track_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'week', 'car', ['car_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'week', type_='foreignkey')
    op.drop_constraint(None, 'week', type_='foreignkey')
    op.drop_column('week', 'end_date')
    op.drop_column('week', 'start_date')
    op.drop_column('week', 'track_id')
    op.drop_column('week', 'car_id')
    # ### end Alembic commands ###
