"""garage61 auth table

Revision ID: 3cf924f12f04
Revises: 3a38c52e6d69
Create Date: 2024-09-19 20:48:22.798823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf924f12f04'
down_revision: Union[str, None] = '3a38c52e6d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garage61_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linked_account_id', sa.UUID(), nullable=False),
    sa.Column('garage61_access_token', sa.String(), nullable=False),
    sa.Column('garage61_refresh_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_account_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garage61_user_id'), 'garage61_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garage61_user_id'), table_name='garage61_user')
    op.drop_table('garage61_user')
    # ### end Alembic commands ###
