"""displayname for users

Revision ID: 9cb8fc633e8a
Revises: 76e2f3541240
Create Date: 2024-09-05 15:22:01.627244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb8fc633e8a'
down_revision: Union[str, None] = '76e2f3541240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'display_name')
    # ### end Alembic commands ###
