"""cars and tracks tables

Revision ID: ce06b3bd7212
Revises: 8a23b2e39ff7
Create Date: 2024-09-13 15:17:18.393737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce06b3bd7212'
down_revision: Union[str, None] = '8a23b2e39ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(), nullable=False),
    sa.Column('car_category', sa.Enum('SPORTS_CAR', 'FORMULA_CAR', 'OVAL', 'DIRT_OVAL', name='carcategory'), nullable=True),
    sa.Column('iracing_car_id', sa.Integer(), nullable=True),
    sa.Column('garage61_car_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_name')
    )
    op.create_index(op.f('ix_car_id'), 'car', ['id'], unique=False)
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', sa.String(), nullable=True),
    sa.Column('iracing_id', sa.Integer(), nullable=True),
    sa.Column('iracing_image_url', sa.String(), nullable=True),
    sa.Column('garage61_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_id'), 'track', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_id'), table_name='track')
    op.drop_table('track')
    op.drop_index(op.f('ix_car_id'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
